// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC09N6NbY7IRz-_LcPyPE0TDhRoGZ_sqE4',
    appId: '1:966326210845:web:5de6eb9fbb42f6b54c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    authDomain: 'fluttertest-b9880.firebaseapp.com',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    measurementId: 'G-938J6QXRW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1aDjgIWgN9G3WlodF92sTYouf4uj5rfI',
    appId: '1:966326210845:android:56219538c0cac5324c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9pAezHRL_q3sJcnMFE2SWfeEQE5gq6Eo',
    appId: '1:966326210845:ios:d43e2991f1ed1c344c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    iosClientId: '966326210845-i7jb09v2e9ot8hdns6sn3tqbad27v9vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9pAezHRL_q3sJcnMFE2SWfeEQE5gq6Eo',
    appId: '1:966326210845:ios:d43e2991f1ed1c344c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    iosClientId: '966326210845-i7jb09v2e9ot8hdns6sn3tqbad27v9vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC09N6NbY7IRz-_LcPyPE0TDhRoGZ_sqE4',
    appId: '1:966326210845:web:70b77267337ea6d34c51f4',
    messagingSenderId: '966326210845',
    projectId: 'fluttertest-b9880',
    authDomain: 'fluttertest-b9880.firebaseapp.com',
    databaseURL: 'https://fluttertest-b9880-default-rtdb.firebaseio.com',
    storageBucket: 'fluttertest-b9880.appspot.com',
    measurementId: 'G-P8C9BBGZ9T',
  );
}
